--[[
  EMS API Documentation
 
  Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps
 
  OpenAPI spec version: 0.0.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- push_data_object_extras class
local push_data_object_extras = {}
local push_data_object_extras_mt = {
	__name = "push_data_object_extras";
	__index = push_data_object_extras;
}

local function cast_push_data_object_extras(t)
	return setmetatable(t, push_data_object_extras_mt)
end

local function new_push_data_object_extras(message)
	return cast_push_data_object_extras({
		["message"] = message;
	})
end

return {
	cast = cast_push_data_object_extras;
	new = new_push_data_object_extras;
}
