--[[
  EMS API Documentation
 
  Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps
 
  OpenAPI spec version: 0.0.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- update_group_object class
local update_group_object = {}
local update_group_object_mt = {
	__name = "update_group_object";
	__index = update_group_object;
}

local function cast_update_group_object(t)
	return setmetatable(t, update_group_object_mt)
end

local function new_update_group_object(field_name, users)
	return cast_update_group_object({
		["fieldName"] = field_name;
		["users"] = users;
	})
end

return {
	cast = cast_update_group_object;
	new = new_update_group_object;
}
