--[[
  EMS API Documentation
 
  Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps
 
  OpenAPI spec version: 0.0.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- user_token_object class
local user_token_object = {}
local user_token_object_mt = {
	__name = "user_token_object";
	__index = user_token_object;
}

local function cast_user_token_object(t)
	return setmetatable(t, user_token_object_mt)
end

local function new_user_token_object(id, username, _meta, sessiontoken)
	return cast_user_token_object({
		["id"] = id;
		["username"] = username;
		["_meta"] = _meta;
		["sessiontoken"] = sessiontoken;
	})
end

return {
	cast = cast_user_token_object;
	new = new_user_token_object;
}
