# This file is auto-generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen)
# Please replace "TEST_VALUE" with a proper value and uncomment the code for testing the function

Describe 'IO.Swagger UsersApi' {
    Context 'UsersApi' {
        It 'Invoke-UsersApiAddUser' {
            $ret = Invoke-PetApiGetPetById -body "TEST_VALUE" -xEmbarcaderoApplicationId "TEST_VALUE" -xEmbarcaderoAppSecret "TEST_VALUE" -xEmbarcaderoMasterSecret "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'UsersApi' {
        It 'Invoke-UsersApiDeleteUser' {
            $ret = Invoke-PetApiGetPetById -id "TEST_VALUE" -xEmbarcaderoApplicationId "TEST_VALUE" -xEmbarcaderoAppSecret "TEST_VALUE" -xEmbarcaderoMasterSecret "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'UsersApi' {
        It 'Invoke-UsersApiGetUser' {
            $ret = Invoke-PetApiGetPetById -id "TEST_VALUE" -xEmbarcaderoApplicationId "TEST_VALUE" -xEmbarcaderoAppSecret "TEST_VALUE" -xEmbarcaderoMasterSecret "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'UsersApi' {
        It 'Invoke-UsersApiGetUserFields' {
            $ret = Invoke-PetApiGetPetById -xEmbarcaderoApplicationId "TEST_VALUE" -xEmbarcaderoAppSecret "TEST_VALUE" -xEmbarcaderoMasterSecret "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'UsersApi' {
        It 'Invoke-UsersApiGetUserGroups' {
            $ret = Invoke-PetApiGetPetById -id "TEST_VALUE" -xEmbarcaderoApplicationId "TEST_VALUE" -xEmbarcaderoAppSecret "TEST_VALUE" -xEmbarcaderoMasterSecret "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'UsersApi' {
        It 'Invoke-UsersApiGetUsers' {
            $ret = Invoke-PetApiGetPetById -xEmbarcaderoApplicationId "TEST_VALUE" -xEmbarcaderoAppSecret "TEST_VALUE" -xEmbarcaderoMasterSecret "TEST_VALUE" -skip "TEST_VALUE" -limit "TEST_VALUE" -order "TEST_VALUE" -where "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'UsersApi' {
        It 'Invoke-UsersApiLoginUser' {
            $ret = Invoke-PetApiGetPetById -body "TEST_VALUE" -xEmbarcaderoApplicationId "TEST_VALUE" -xEmbarcaderoAppSecret "TEST_VALUE" -xEmbarcaderoMasterSecret "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'UsersApi' {
        It 'Invoke-UsersApiLogoutUser' {
            $ret = Invoke-PetApiGetPetById -xEmbarcaderoApplicationId "TEST_VALUE" -xEmbarcaderoAppSecret "TEST_VALUE" -xEmbarcaderoMasterSecret "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'UsersApi' {
        It 'Invoke-UsersApiSignupUser' {
            $ret = Invoke-PetApiGetPetById -body "TEST_VALUE" -xEmbarcaderoApplicationId "TEST_VALUE" -xEmbarcaderoAppSecret "TEST_VALUE" -xEmbarcaderoMasterSecret "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'UsersApi' {
        It 'Invoke-UsersApiUpdateUser' {
            $ret = Invoke-PetApiGetPetById -id "TEST_VALUE" -body "TEST_VALUE" -xEmbarcaderoApplicationId "TEST_VALUE" -xEmbarcaderoAppSecret "TEST_VALUE" -xEmbarcaderoMasterSecret "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

}
