/**
 * EMS API Documentation
 * Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _SWG_SWGVersionApi_H_
#define _SWG_SWGVersionApi_H_

#include "SWGHttpRequest.h"

#include <QString>
#include "SWGVersionObject.h"

#include <QObject>

namespace Swagger {

class SWGVersionApi: public QObject {
    Q_OBJECT

public:
    SWGVersionApi();
    SWGVersionApi(QString host, QString basePath);
    ~SWGVersionApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void getVersion(QString* x_embarcadero_application_id, QString* x_embarcadero_app_secret, QString* x_embarcadero_master_secret);
    
private:
    void getVersionCallback (SWGHttpRequestWorker * worker);
    
signals:
    void getVersionSignal(SWGVersionObject* summary);
    
    void getVersionSignalE(SWGVersionObject* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void getVersionSignalEFull(SWGHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
