# EMS API Documentation
#
# Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps
#
# OpenAPI spec version: 0.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' @title Groups operations
#' @description swagger.Groups
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' add_group Add Group
#'
#'
#' delete_group Delete Group
#'
#'
#' get_group Get Group
#'
#'
#' get_group_fields Get Fields
#'
#'
#' get_groups Get Groups
#'
#'
#' update_group Update Group
#'
#' }
#'
#' @export
GroupsApi <- R6::R6Class(
  'GroupsApi',
  public = list(
    userAgent = "Swagger-Codegen/1.0.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    add_group = function(body, x_embarcadero_application_id, x_embarcadero_app_secret, x_embarcadero_master_secret, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`x_embarcadero_application_id`)) {
        headerParams['X-Embarcadero-Application-Id'] <- `x_embarcadero_application_id`
      }

      if (!missing(`x_embarcadero_app_secret`)) {
        headerParams['X-Embarcadero-App-Secret'] <- `x_embarcadero_app_secret`
      }

      if (!missing(`x_embarcadero_master_secret`)) {
        headerParams['X-Embarcadero-Master-Secret'] <- `x_embarcadero_master_secret`
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/groups"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    delete_group = function(item, x_embarcadero_application_id, x_embarcadero_app_secret, x_embarcadero_master_secret, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`x_embarcadero_application_id`)) {
        headerParams['X-Embarcadero-Application-Id'] <- `x_embarcadero_application_id`
      }

      if (!missing(`x_embarcadero_app_secret`)) {
        headerParams['X-Embarcadero-App-Secret'] <- `x_embarcadero_app_secret`
      }

      if (!missing(`x_embarcadero_master_secret`)) {
        headerParams['X-Embarcadero-Master-Secret'] <- `x_embarcadero_master_secret`
      }

      urlPath <- "/groups/{item}"
      if (!missing(`item`)) {
        urlPath <- gsub(paste0("\\{", "item", "\\}"), `item`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_group = function(item, x_embarcadero_application_id, x_embarcadero_app_secret, x_embarcadero_master_secret, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`x_embarcadero_application_id`)) {
        headerParams['X-Embarcadero-Application-Id'] <- `x_embarcadero_application_id`
      }

      if (!missing(`x_embarcadero_app_secret`)) {
        headerParams['X-Embarcadero-App-Secret'] <- `x_embarcadero_app_secret`
      }

      if (!missing(`x_embarcadero_master_secret`)) {
        headerParams['X-Embarcadero-Master-Secret'] <- `x_embarcadero_master_secret`
      }

      urlPath <- "/groups/{item}"
      if (!missing(`item`)) {
        urlPath <- gsub(paste0("\\{", "item", "\\}"), `item`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- GroupObject$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_group_fields = function(x_embarcadero_application_id, x_embarcadero_app_secret, x_embarcadero_master_secret, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`x_embarcadero_application_id`)) {
        headerParams['X-Embarcadero-Application-Id'] <- `x_embarcadero_application_id`
      }

      if (!missing(`x_embarcadero_app_secret`)) {
        headerParams['X-Embarcadero-App-Secret'] <- `x_embarcadero_app_secret`
      }

      if (!missing(`x_embarcadero_master_secret`)) {
        headerParams['X-Embarcadero-Master-Secret'] <- `x_embarcadero_master_secret`
      }

      urlPath <- "/groups/fields"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- FieldGroupObject$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_groups = function(x_embarcadero_application_id, x_embarcadero_app_secret, x_embarcadero_master_secret, skip, limit, order, where, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`x_embarcadero_application_id`)) {
        headerParams['X-Embarcadero-Application-Id'] <- `x_embarcadero_application_id`
      }

      if (!missing(`x_embarcadero_app_secret`)) {
        headerParams['X-Embarcadero-App-Secret'] <- `x_embarcadero_app_secret`
      }

      if (!missing(`x_embarcadero_master_secret`)) {
        headerParams['X-Embarcadero-Master-Secret'] <- `x_embarcadero_master_secret`
      }

      if (!missing(`skip`)) {
        queryParams['skip'] <- skip
      }

      if (!missing(`limit`)) {
        queryParams['limit'] <- limit
      }

      if (!missing(`order`)) {
        queryParams['order'] <- order
      }

      if (!missing(`where`)) {
        queryParams['where'] <- where
      }

      urlPath <- "/groups"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- GroupObject$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    update_group = function(item, body, x_embarcadero_application_id, x_embarcadero_app_secret, x_embarcadero_master_secret, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`x_embarcadero_application_id`)) {
        headerParams['X-Embarcadero-Application-Id'] <- `x_embarcadero_application_id`
      }

      if (!missing(`x_embarcadero_app_secret`)) {
        headerParams['X-Embarcadero-App-Secret'] <- `x_embarcadero_app_secret`
      }

      if (!missing(`x_embarcadero_master_secret`)) {
        headerParams['X-Embarcadero-Master-Secret'] <- `x_embarcadero_master_secret`
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/groups/{item}"
      if (!missing(`item`)) {
        urlPath <- gsub(paste0("\\{", "item", "\\}"), `item`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "PUT",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- UpdatedGroupObject$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
