# EMS API Documentation
#
# Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps
#
# OpenAPI spec version: 0.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' MetaInstallationObject Class
#'
#' @field creator 
#' @field created 
#' @field updated 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MetaInstallationObject <- R6::R6Class(
  'MetaInstallationObject',
  public = list(
    `creator` = NULL,
    `created` = NULL,
    `updated` = NULL,
    initialize = function(`creator`, `created`, `updated`){
      if (!missing(`creator`)) {
        stopifnot(is.character(`creator`), length(`creator`) == 1)
        self$`creator` <- `creator`
      }
      if (!missing(`created`)) {
        stopifnot(is.character(`created`), length(`created`) == 1)
        self$`created` <- `created`
      }
      if (!missing(`updated`)) {
        stopifnot(is.character(`updated`), length(`updated`) == 1)
        self$`updated` <- `updated`
      }
    },
    toJSON = function() {
      MetaInstallationObjectObject <- list()
      if (!is.null(self$`creator`)) {
        MetaInstallationObjectObject[['creator']] <- self$`creator`
      }
      if (!is.null(self$`created`)) {
        MetaInstallationObjectObject[['created']] <- self$`created`
      }
      if (!is.null(self$`updated`)) {
        MetaInstallationObjectObject[['updated']] <- self$`updated`
      }

      MetaInstallationObjectObject
    },
    fromJSON = function(MetaInstallationObjectJson) {
      MetaInstallationObjectObject <- jsonlite::fromJSON(MetaInstallationObjectJson)
      if (!is.null(MetaInstallationObjectObject$`creator`)) {
        self$`creator` <- MetaInstallationObjectObject$`creator`
      }
      if (!is.null(MetaInstallationObjectObject$`created`)) {
        self$`created` <- MetaInstallationObjectObject$`created`
      }
      if (!is.null(MetaInstallationObjectObject$`updated`)) {
        self$`updated` <- MetaInstallationObjectObject$`updated`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "creator": %s,
           "created": %s,
           "updated": %s
        }',
        self$`creator`,
        self$`created`,
        self$`updated`
      )
    },
    fromJSONString = function(MetaInstallationObjectJson) {
      MetaInstallationObjectObject <- jsonlite::fromJSON(MetaInstallationObjectJson)
      self$`creator` <- MetaInstallationObjectObject$`creator`
      self$`created` <- MetaInstallationObjectObject$`created`
      self$`updated` <- MetaInstallationObjectObject$`updated`
    }
  )
)
