# EMS API Documentation
#
# Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps
#
# OpenAPI spec version: 0.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PushDataObjectAps Class
#'
#' @field alert 
#' @field badge 
#' @field sound 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PushDataObjectAps <- R6::R6Class(
  'PushDataObjectAps',
  public = list(
    `alert` = NULL,
    `badge` = NULL,
    `sound` = NULL,
    initialize = function(`alert`, `badge`, `sound`){
      if (!missing(`alert`)) {
        stopifnot(is.character(`alert`), length(`alert`) == 1)
        self$`alert` <- `alert`
      }
      if (!missing(`badge`)) {
        stopifnot(is.character(`badge`), length(`badge`) == 1)
        self$`badge` <- `badge`
      }
      if (!missing(`sound`)) {
        stopifnot(is.character(`sound`), length(`sound`) == 1)
        self$`sound` <- `sound`
      }
    },
    toJSON = function() {
      PushDataObjectApsObject <- list()
      if (!is.null(self$`alert`)) {
        PushDataObjectApsObject[['alert']] <- self$`alert`
      }
      if (!is.null(self$`badge`)) {
        PushDataObjectApsObject[['badge']] <- self$`badge`
      }
      if (!is.null(self$`sound`)) {
        PushDataObjectApsObject[['sound']] <- self$`sound`
      }

      PushDataObjectApsObject
    },
    fromJSON = function(PushDataObjectApsJson) {
      PushDataObjectApsObject <- jsonlite::fromJSON(PushDataObjectApsJson)
      if (!is.null(PushDataObjectApsObject$`alert`)) {
        self$`alert` <- PushDataObjectApsObject$`alert`
      }
      if (!is.null(PushDataObjectApsObject$`badge`)) {
        self$`badge` <- PushDataObjectApsObject$`badge`
      }
      if (!is.null(PushDataObjectApsObject$`sound`)) {
        self$`sound` <- PushDataObjectApsObject$`sound`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "alert": %s,
           "badge": %s,
           "sound": %s
        }',
        self$`alert`,
        self$`badge`,
        self$`sound`
      )
    },
    fromJSONString = function(PushDataObjectApsJson) {
      PushDataObjectApsObject <- jsonlite::fromJSON(PushDataObjectApsJson)
      self$`alert` <- PushDataObjectApsObject$`alert`
      self$`badge` <- PushDataObjectApsObject$`badge`
      self$`sound` <- PushDataObjectApsObject$`sound`
    }
  )
)
