# EMS API Documentation
#
# Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps
#
# OpenAPI spec version: 0.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' UpdatedGroupObject Class
#'
#' @field updated 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UpdatedGroupObject <- R6::R6Class(
  'UpdatedGroupObject',
  public = list(
    `updated` = NULL,
    initialize = function(`updated`){
      if (!missing(`updated`)) {
        stopifnot(is.character(`updated`), length(`updated`) == 1)
        self$`updated` <- `updated`
      }
    },
    toJSON = function() {
      UpdatedGroupObjectObject <- list()
      if (!is.null(self$`updated`)) {
        UpdatedGroupObjectObject[['updated']] <- self$`updated`
      }

      UpdatedGroupObjectObject
    },
    fromJSON = function(UpdatedGroupObjectJson) {
      UpdatedGroupObjectObject <- jsonlite::fromJSON(UpdatedGroupObjectJson)
      if (!is.null(UpdatedGroupObjectObject$`updated`)) {
        self$`updated` <- UpdatedGroupObjectObject$`updated`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "updated": %s
        }',
        self$`updated`
      )
    },
    fromJSONString = function(UpdatedGroupObjectJson) {
      UpdatedGroupObjectObject <- jsonlite::fromJSON(UpdatedGroupObjectJson)
      self$`updated` <- UpdatedGroupObjectObject$`updated`
    }
  )
)
