/**
* EMS API Documentation
* Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps
*
* OpenAPI spec version: 0.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.apis

import io.swagger.client.models.VersionObject

import io.swagger.client.infrastructure.*

class VersionApi(basePath: kotlin.String = "http://localhost:8080") : ApiClient(basePath) {

    /**
    * Get version
    *  |      Used to retrieve the &#x60;Version&#x60; of the EMS Server.
    * @param xEmbarcaderoApplicationId  (optional)
    * @param xEmbarcaderoAppSecret  (optional)
    * @param xEmbarcaderoMasterSecret  (optional)
    * @return VersionObject
    */
    @Suppress("UNCHECKED_CAST")
    fun getVersion(xEmbarcaderoApplicationId: kotlin.String, xEmbarcaderoAppSecret: kotlin.String, xEmbarcaderoMasterSecret: kotlin.String) : VersionObject {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: MultiValueMap = mapOf()
        
        val contentHeaders: kotlin.collections.Map<kotlin.String,kotlin.String> = mapOf()
        val acceptsHeaders: kotlin.collections.Map<kotlin.String,kotlin.String> = mapOf("Accept" to "application/json")
        val localVariableHeaders: kotlin.collections.MutableMap<kotlin.String,kotlin.String> = mutableMapOf("X-Embarcadero-Application-Id" to xEmbarcaderoApplicationId, "X-Embarcadero-App-Secret" to xEmbarcaderoAppSecret, "X-Embarcadero-Master-Secret" to xEmbarcaderoMasterSecret)
        localVariableHeaders.putAll(contentHeaders)
        localVariableHeaders.putAll(acceptsHeaders)
        
        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/version",
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val response = request<VersionObject>(
            localVariableConfig,
            localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as VersionObject
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
            else -> throw kotlin.IllegalStateException("Undefined ResponseType.")
        }
    }

}
