//
// FieldsEdgeModuleObject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class FieldsEdgeModuleObject: JSONEncodable {

    public var name: String?
    public var fields: [FieldObjectFields]?
    public var custom: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["fields"] = self.fields?.encodeToJSON()
        nillableDictionary["custom"] = self.custom

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

