//
// InstallationObject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InstallationObject: JSONEncodable {
    public enum DeviceType: String { 
        case Ios = "ios"
        case Android = "android"
    }
    public var id: String?
    public var deviceToken: String?
    public var deviceType: DeviceType?
    public var meta: MetaInstallationObject?
    public var channels: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["_id"] = self.id
        nillableDictionary["deviceToken"] = self.deviceToken
        nillableDictionary["deviceType"] = self.deviceType?.rawValue
        nillableDictionary["_meta"] = self.meta?.encodeToJSON()
        nillableDictionary["channels"] = self.channels?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
