# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule EMSAPIDocumentation.Model.PushWhereObject do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"deviceType",
    :"deviceToken"
  ]

  @type t :: %__MODULE__{
    :"deviceType" => String.t,
    :"deviceToken" => PushWhereObjectDeviceToken
  }
end

defimpl Poison.Decoder, for: EMSAPIDocumentation.Model.PushWhereObject do
  import EMSAPIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"deviceToken", :struct, EMSAPIDocumentation.Model.PushWhereObjectDeviceToken, options)
  end
end

