# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule EMSAPIDocumentation.Model.UpdateInstallationObject do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"channels"
  ]

  @type t :: %__MODULE__{
    :"channels" => [String.t]
  }
end

defimpl Poison.Decoder, for: EMSAPIDocumentation.Model.UpdateInstallationObject do
  def decode(value, _options) do
    value
  end
end

