# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule EMSAPIDocumentation.Model.UserObject do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"username",
    :"_meta"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"username" => String.t,
    :"_meta" => MetaObject
  }
end

defimpl Poison.Decoder, for: EMSAPIDocumentation.Model.UserObject do
  import EMSAPIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"_meta", :struct, EMSAPIDocumentation.Model.MetaObject, options)
  end
end

