/* 
 * EMS API Documentation
 *
 * Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InstallationAddObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InstallationAddObjectTests
    {
        // TODO uncomment below to declare an instance variable for InstallationAddObject
        //private InstallationAddObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InstallationAddObject
            //instance = new InstallationAddObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InstallationAddObject
        /// </summary>
        [Test]
        public void InstallationAddObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InstallationAddObject
            //Assert.IsInstanceOfType<InstallationAddObject> (instance, "variable 'instance' is a InstallationAddObject");
        }


        /// <summary>
        /// Test the property 'DeviceToken'
        /// </summary>
        [Test]
        public void DeviceTokenTest()
        {
            // TODO unit test for the property 'DeviceToken'
        }
        /// <summary>
        /// Test the property 'DeviceType'
        /// </summary>
        [Test]
        public void DeviceTypeTest()
        {
            // TODO unit test for the property 'DeviceType'
        }
        /// <summary>
        /// Test the property 'Channels'
        /// </summary>
        [Test]
        public void ChannelsTest()
        {
            // TODO unit test for the property 'Channels'
        }

    }

}
