{-
   EMS API Documentation

   Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps

   OpenAPI spec version: 2.0
   EMS API Documentation API version: 0.0.0
   Generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
-}

{-|
Module : EMSAPIDocumentation.API.ApiDoc
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module EMSAPIDocumentation.API.ApiDoc where

import EMSAPIDocumentation.Core
import EMSAPIDocumentation.MimeTypes
import EMSAPIDocumentation.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** ApiDoc

-- *** aPI

-- | @GET \/api@
-- 
-- Get API EndPoints
-- 
--  |      Used to retrieve all the API EndPoints.
-- 
-- Note: Has 'Produces' instances, but no response schema
-- 
aPI 
  :: EMSAPIDocumentationRequest API MimeNoContent res MimeJSON
aPI =
  _mkRequest "GET" ["/api"]

data API  
instance HasOptionalParam API XEmbarcaderoApplicationId where
  applyOptionalParam req (XEmbarcaderoApplicationId xs) =
    req `setHeader` toHeader ("X-Embarcadero-Application-Id", xs)
instance HasOptionalParam API XEmbarcaderoAppSecret where
  applyOptionalParam req (XEmbarcaderoAppSecret xs) =
    req `setHeader` toHeader ("X-Embarcadero-App-Secret", xs)
instance HasOptionalParam API XEmbarcaderoMasterSecret where
  applyOptionalParam req (XEmbarcaderoMasterSecret xs) =
    req `setHeader` toHeader ("X-Embarcadero-Master-Secret", xs)
-- | @application/json@
instance Produces API MimeJSON


-- *** getAPIJSONFormat

-- | @GET \/api\/apidoc.json@
-- 
-- Get JSON
-- 
-- Get API in JSON format
-- 
getAPIJSONFormat 
  :: EMSAPIDocumentationRequest GetAPIJSONFormat MimeNoContent NoContent MimeNoContent
getAPIJSONFormat =
  _mkRequest "GET" ["/api/apidoc.json"]

data GetAPIJSONFormat  
instance HasOptionalParam GetAPIJSONFormat XEmbarcaderoApplicationId where
  applyOptionalParam req (XEmbarcaderoApplicationId xs) =
    req `setHeader` toHeader ("X-Embarcadero-Application-Id", xs)
instance HasOptionalParam GetAPIJSONFormat XEmbarcaderoAppSecret where
  applyOptionalParam req (XEmbarcaderoAppSecret xs) =
    req `setHeader` toHeader ("X-Embarcadero-App-Secret", xs)
instance HasOptionalParam GetAPIJSONFormat XEmbarcaderoMasterSecret where
  applyOptionalParam req (XEmbarcaderoMasterSecret xs) =
    req `setHeader` toHeader ("X-Embarcadero-Master-Secret", xs)

-- *** getAPIYAMLFormat

-- | @GET \/api\/apidoc.yaml@
-- 
-- Get YAML
-- 
-- Get API in YAML format
-- 
getAPIYAMLFormat 
  :: EMSAPIDocumentationRequest GetAPIYAMLFormat MimeNoContent NoContent MimeNoContent
getAPIYAMLFormat =
  _mkRequest "GET" ["/api/apidoc.yaml"]

data GetAPIYAMLFormat  
instance HasOptionalParam GetAPIYAMLFormat XEmbarcaderoApplicationId where
  applyOptionalParam req (XEmbarcaderoApplicationId xs) =
    req `setHeader` toHeader ("X-Embarcadero-Application-Id", xs)
instance HasOptionalParam GetAPIYAMLFormat XEmbarcaderoAppSecret where
  applyOptionalParam req (XEmbarcaderoAppSecret xs) =
    req `setHeader` toHeader ("X-Embarcadero-App-Secret", xs)
instance HasOptionalParam GetAPIYAMLFormat XEmbarcaderoMasterSecret where
  applyOptionalParam req (XEmbarcaderoMasterSecret xs) =
    req `setHeader` toHeader ("X-Embarcadero-Master-Secret", xs)

-- *** getAPIYAMLFormatEndPoint

-- | @GET \/api\/{item}\/apidoc.yaml@
-- 
-- Get API EndPoint
-- 
--  |      Used to retrieve an EndPoint for the API EndPoints.
-- 
-- Note: Has 'Produces' instances, but no response schema
-- 
getAPIYAMLFormatEndPoint 
  :: Item -- ^ "item" -  Path Segment to an EndPoint
  -> EMSAPIDocumentationRequest GetAPIYAMLFormatEndPoint MimeNoContent res MimeJSON
getAPIYAMLFormatEndPoint (Item item) =
  _mkRequest "GET" ["/api/",toPath item,"/apidoc.yaml"]

data GetAPIYAMLFormatEndPoint  
instance HasOptionalParam GetAPIYAMLFormatEndPoint XEmbarcaderoApplicationId where
  applyOptionalParam req (XEmbarcaderoApplicationId xs) =
    req `setHeader` toHeader ("X-Embarcadero-Application-Id", xs)
instance HasOptionalParam GetAPIYAMLFormatEndPoint XEmbarcaderoAppSecret where
  applyOptionalParam req (XEmbarcaderoAppSecret xs) =
    req `setHeader` toHeader ("X-Embarcadero-App-Secret", xs)
instance HasOptionalParam GetAPIYAMLFormatEndPoint XEmbarcaderoMasterSecret where
  applyOptionalParam req (XEmbarcaderoMasterSecret xs) =
    req `setHeader` toHeader ("X-Embarcadero-Master-Secret", xs)
-- | @application/json@
instance Produces GetAPIYAMLFormatEndPoint MimeJSON

