//
// UseridObject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UseridObject: Codable {

    public var _id: String

    public init(_id: String) {
        self._id = _id
    }


}

