/*
 * EMS API Documentation
 *
 * Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
	"fmt"
	"github.com/antihax/optional"
)

// Linger please
var (
	_ context.Context
)

type UsersApiService service

/* 
UsersApiService Add User
 |      Used to add a new &#x60;User&#x60; object to the EMS database.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param body Object to add a new EMS User in the EMS Server
 * @param optional nil or *AddUserOpts - Optional Parameters:
     * @param "XEmbarcaderoApplicationId" (optional.String) - 
     * @param "XEmbarcaderoAppSecret" (optional.String) - 
     * @param "XEmbarcaderoMasterSecret" (optional.String) - 

@return UseridObject
*/

type AddUserOpts struct { 
	XEmbarcaderoApplicationId optional.String
	XEmbarcaderoAppSecret optional.String
	XEmbarcaderoMasterSecret optional.String
}

func (a *UsersApiService) AddUser(ctx context.Context, body UserCredentialsObject, localVarOptionals *AddUserOpts) (UseridObject, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Post")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue UseridObject
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/users"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoApplicationId.IsSet() {
		localVarHeaderParams["X-Embarcadero-Application-Id"] = parameterToString(localVarOptionals.XEmbarcaderoApplicationId.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoAppSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-App-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoAppSecret.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoMasterSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-Master-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoMasterSecret.Value(), "")
	}
	// body params
	localVarPostBody = &body
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 201 {
			var v UseridObject
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
UsersApiService Delete User
 |      Used to delete a &#x60;User&#x60;. **id** is the unique EMS User identifier (UID) in the EMS database.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id A user ID
 * @param optional nil or *DeleteUserOpts - Optional Parameters:
     * @param "XEmbarcaderoApplicationId" (optional.String) - 
     * @param "XEmbarcaderoAppSecret" (optional.String) - 
     * @param "XEmbarcaderoMasterSecret" (optional.String) - 


*/

type DeleteUserOpts struct { 
	XEmbarcaderoApplicationId optional.String
	XEmbarcaderoAppSecret optional.String
	XEmbarcaderoMasterSecret optional.String
}

func (a *UsersApiService) DeleteUser(ctx context.Context, id string, localVarOptionals *DeleteUserOpts) (*http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Delete")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/users/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", fmt.Sprintf("%v", id), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoApplicationId.IsSet() {
		localVarHeaderParams["X-Embarcadero-Application-Id"] = parameterToString(localVarOptionals.XEmbarcaderoApplicationId.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoAppSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-App-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoAppSecret.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoMasterSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-Master-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoMasterSecret.Value(), "")
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarHttpResponse, err
	}


	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		return localVarHttpResponse, newErr
	}

	return localVarHttpResponse, nil
}

/* 
UsersApiService Get User
 |      Used to retrieve all data from a &#x60;User&#x60;. **id** is the unique EMS User identifier (UID) in the EMS database.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id A user ID
 * @param optional nil or *GetUserOpts - Optional Parameters:
     * @param "XEmbarcaderoApplicationId" (optional.String) - 
     * @param "XEmbarcaderoAppSecret" (optional.String) - 
     * @param "XEmbarcaderoMasterSecret" (optional.String) - 

@return UserObject
*/

type GetUserOpts struct { 
	XEmbarcaderoApplicationId optional.String
	XEmbarcaderoAppSecret optional.String
	XEmbarcaderoMasterSecret optional.String
}

func (a *UsersApiService) GetUser(ctx context.Context, id string, localVarOptionals *GetUserOpts) (UserObject, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Get")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue UserObject
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/users/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", fmt.Sprintf("%v", id), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoApplicationId.IsSet() {
		localVarHeaderParams["X-Embarcadero-Application-Id"] = parameterToString(localVarOptionals.XEmbarcaderoApplicationId.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoAppSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-App-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoAppSecret.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoMasterSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-Master-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoMasterSecret.Value(), "")
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v UserObject
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
UsersApiService Get Fields
 |      Used to retrieve all the &#x60;field names&#x60; of the EMS Users (including the custom fields).
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param optional nil or *GetUserFieldsOpts - Optional Parameters:
     * @param "XEmbarcaderoApplicationId" (optional.String) - 
     * @param "XEmbarcaderoAppSecret" (optional.String) - 
     * @param "XEmbarcaderoMasterSecret" (optional.String) - 

@return []FieldObject
*/

type GetUserFieldsOpts struct { 
	XEmbarcaderoApplicationId optional.String
	XEmbarcaderoAppSecret optional.String
	XEmbarcaderoMasterSecret optional.String
}

func (a *UsersApiService) GetUserFields(ctx context.Context, localVarOptionals *GetUserFieldsOpts) ([]FieldObject, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Get")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue []FieldObject
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/users/fields"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoApplicationId.IsSet() {
		localVarHeaderParams["X-Embarcadero-Application-Id"] = parameterToString(localVarOptionals.XEmbarcaderoApplicationId.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoAppSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-App-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoAppSecret.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoMasterSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-Master-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoMasterSecret.Value(), "")
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v []FieldObject
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
UsersApiService Get User Groups
 |      Used to retrieve the EMS Groups the EMS User belongs to. **id** is the unique EMS User identifier (UID) in the EMS database.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id A user ID
 * @param optional nil or *GetUserGroupsOpts - Optional Parameters:
     * @param "XEmbarcaderoApplicationId" (optional.String) - 
     * @param "XEmbarcaderoAppSecret" (optional.String) - 
     * @param "XEmbarcaderoMasterSecret" (optional.String) - 

@return []GroupName
*/

type GetUserGroupsOpts struct { 
	XEmbarcaderoApplicationId optional.String
	XEmbarcaderoAppSecret optional.String
	XEmbarcaderoMasterSecret optional.String
}

func (a *UsersApiService) GetUserGroups(ctx context.Context, id string, localVarOptionals *GetUserGroupsOpts) ([]GroupName, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Get")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue []GroupName
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/users/{id}/groups"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", fmt.Sprintf("%v", id), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoApplicationId.IsSet() {
		localVarHeaderParams["X-Embarcadero-Application-Id"] = parameterToString(localVarOptionals.XEmbarcaderoApplicationId.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoAppSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-App-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoAppSecret.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoMasterSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-Master-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoMasterSecret.Value(), "")
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v []GroupName
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
UsersApiService Get Users
 |      Used to retrieve all data from &#x60;Users&#x60;.      Optional query param of **skip, limit, order, where** determines       size of returned array, filtered and order by.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param optional nil or *GetUsersOpts - Optional Parameters:
     * @param "XEmbarcaderoApplicationId" (optional.String) - 
     * @param "XEmbarcaderoAppSecret" (optional.String) - 
     * @param "XEmbarcaderoMasterSecret" (optional.String) - 
     * @param "Skip" (optional.Float32) -  users skipped
     * @param "Limit" (optional.Float32) -  maximum number of results to return
     * @param "Order" (optional.Float32) -  order ascending or descending (asc, desc)
     * @param "Where" (optional.String) -  filter operators (lt, lte, gt, gte, eq, neq, like, nlike)

@return []UserObject
*/

type GetUsersOpts struct { 
	XEmbarcaderoApplicationId optional.String
	XEmbarcaderoAppSecret optional.String
	XEmbarcaderoMasterSecret optional.String
	Skip optional.Float32
	Limit optional.Float32
	Order optional.Float32
	Where optional.String
}

func (a *UsersApiService) GetUsers(ctx context.Context, localVarOptionals *GetUsersOpts) ([]UserObject, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Get")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue []UserObject
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/users"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if localVarOptionals != nil && localVarOptionals.Skip.IsSet() {
		localVarQueryParams.Add("skip", parameterToString(localVarOptionals.Skip.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Limit.IsSet() {
		localVarQueryParams.Add("limit", parameterToString(localVarOptionals.Limit.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Order.IsSet() {
		localVarQueryParams.Add("order", parameterToString(localVarOptionals.Order.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Where.IsSet() {
		localVarQueryParams.Add("where", parameterToString(localVarOptionals.Where.Value(), ""))
	}
	// to determine the Content-Type header
	localVarHttpContentTypes := []string{}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoApplicationId.IsSet() {
		localVarHeaderParams["X-Embarcadero-Application-Id"] = parameterToString(localVarOptionals.XEmbarcaderoApplicationId.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoAppSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-App-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoAppSecret.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoMasterSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-Master-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoMasterSecret.Value(), "")
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v []UserObject
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
UsersApiService Log In
 |      Logs in to the EMS Server with a specific EMS User.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param body A user object
 * @param optional nil or *LoginUserOpts - Optional Parameters:
     * @param "XEmbarcaderoApplicationId" (optional.String) - 
     * @param "XEmbarcaderoAppSecret" (optional.String) - 
     * @param "XEmbarcaderoMasterSecret" (optional.String) - 

@return UserTokenObject
*/

type LoginUserOpts struct { 
	XEmbarcaderoApplicationId optional.String
	XEmbarcaderoAppSecret optional.String
	XEmbarcaderoMasterSecret optional.String
}

func (a *UsersApiService) LoginUser(ctx context.Context, body UserCredentialsObject, localVarOptionals *LoginUserOpts) (UserTokenObject, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Post")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue UserTokenObject
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/users/login"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoApplicationId.IsSet() {
		localVarHeaderParams["X-Embarcadero-Application-Id"] = parameterToString(localVarOptionals.XEmbarcaderoApplicationId.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoAppSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-App-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoAppSecret.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoMasterSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-Master-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoMasterSecret.Value(), "")
	}
	// body params
	localVarPostBody = &body
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v UserTokenObject
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
UsersApiService sPostLogoutSummaryTitle
sPostLogoutSummaryDesc
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param optional nil or *LogoutUserOpts - Optional Parameters:
     * @param "XEmbarcaderoApplicationId" (optional.String) - 
     * @param "XEmbarcaderoAppSecret" (optional.String) - 
     * @param "XEmbarcaderoMasterSecret" (optional.String) - 


*/

type LogoutUserOpts struct { 
	XEmbarcaderoApplicationId optional.String
	XEmbarcaderoAppSecret optional.String
	XEmbarcaderoMasterSecret optional.String
}

func (a *UsersApiService) LogoutUser(ctx context.Context, localVarOptionals *LogoutUserOpts) (*http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Post")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/users/logout"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoApplicationId.IsSet() {
		localVarHeaderParams["X-Embarcadero-Application-Id"] = parameterToString(localVarOptionals.XEmbarcaderoApplicationId.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoAppSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-App-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoAppSecret.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoMasterSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-Master-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoMasterSecret.Value(), "")
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarHttpResponse, err
	}


	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		return localVarHttpResponse, newErr
	}

	return localVarHttpResponse, nil
}

/* 
UsersApiService Sign Up  User
 |      Signs up to the EMS Server with an appropriate EMS User.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param body Object to sign up a new EMS User in the EMS Server
 * @param optional nil or *SignupUserOpts - Optional Parameters:
     * @param "XEmbarcaderoApplicationId" (optional.String) - 
     * @param "XEmbarcaderoAppSecret" (optional.String) - 
     * @param "XEmbarcaderoMasterSecret" (optional.String) - 

@return UserSignUpResponseObject
*/

type SignupUserOpts struct { 
	XEmbarcaderoApplicationId optional.String
	XEmbarcaderoAppSecret optional.String
	XEmbarcaderoMasterSecret optional.String
}

func (a *UsersApiService) SignupUser(ctx context.Context, body UserCredentialsObject, localVarOptionals *SignupUserOpts) (UserSignUpResponseObject, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Post")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue UserSignUpResponseObject
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/users/signup"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoApplicationId.IsSet() {
		localVarHeaderParams["X-Embarcadero-Application-Id"] = parameterToString(localVarOptionals.XEmbarcaderoApplicationId.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoAppSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-App-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoAppSecret.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoMasterSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-Master-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoMasterSecret.Value(), "")
	}
	// body params
	localVarPostBody = &body
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v UserSignUpResponseObject
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
UsersApiService Update User
 |      Used to update a &#x60;User&#x60;. **id** is the unique EMS User identifier (UID) in the EMS database.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id A user ID
 * @param body Add any fieldName
 * @param optional nil or *UpdateUserOpts - Optional Parameters:
     * @param "XEmbarcaderoApplicationId" (optional.String) - 
     * @param "XEmbarcaderoAppSecret" (optional.String) - 
     * @param "XEmbarcaderoMasterSecret" (optional.String) - 

@return UpdatedObject
*/

type UpdateUserOpts struct { 
	XEmbarcaderoApplicationId optional.String
	XEmbarcaderoAppSecret optional.String
	XEmbarcaderoMasterSecret optional.String
}

func (a *UsersApiService) UpdateUser(ctx context.Context, id string, body UpdateObject, localVarOptionals *UpdateUserOpts) (UpdatedObject, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Put")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue UpdatedObject
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/users/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", fmt.Sprintf("%v", id), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoApplicationId.IsSet() {
		localVarHeaderParams["X-Embarcadero-Application-Id"] = parameterToString(localVarOptionals.XEmbarcaderoApplicationId.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoAppSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-App-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoAppSecret.Value(), "")
	}
	if localVarOptionals != nil && localVarOptionals.XEmbarcaderoMasterSecret.IsSet() {
		localVarHeaderParams["X-Embarcadero-Master-Secret"] = parameterToString(localVarOptionals.XEmbarcaderoMasterSecret.Value(), "")
	}
	// body params
	localVarPostBody = &body
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v UpdatedObject
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}
