/* 
 * EMS API Documentation
 *
 * Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GroupAddObject {
  #[serde(rename = "groupname")]
  groupname: String
}

impl GroupAddObject {
  pub fn new(groupname: String) -> GroupAddObject {
    GroupAddObject {
      groupname: groupname
    }
  }

  pub fn set_groupname(&mut self, groupname: String) {
    self.groupname = groupname;
  }

  pub fn with_groupname(mut self, groupname: String) -> GroupAddObject {
    self.groupname = groupname;
    self
  }

  pub fn groupname(&self) -> &String {
    &self.groupname
  }


}



