export * from './ApiDocApi';
import { ApiDocApi } from './ApiDocApi';
export * from './EdgeModulesApi';
import { EdgeModulesApi } from './EdgeModulesApi';
export * from './EdgeModulesInvokersApi';
import { EdgeModulesInvokersApi } from './EdgeModulesInvokersApi';
export * from './GroupsApi';
import { GroupsApi } from './GroupsApi';
export * from './InstallationsApi';
import { InstallationsApi } from './InstallationsApi';
export * from './PushApi';
import { PushApi } from './PushApi';
export * from './UsersApi';
import { UsersApi } from './UsersApi';
export * from './VersionApi';
import { VersionApi } from './VersionApi';
export const APIS = [ApiDocApi, EdgeModulesApi, EdgeModulesInvokersApi, GroupsApi, InstallationsApi, PushApi, UsersApi, VersionApi];
