/*
 * EMS API Documentation
 * Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiDocApi
 */
@Ignore
public class ApiDocApiTest {

    private final ApiDocApi api = new ApiDocApi();

    
    /**
     * Get API EndPoints
     *
     *  |      Used to retrieve all the API EndPoints.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void aPITest() throws ApiException {
        String xEmbarcaderoApplicationId = null;
        String xEmbarcaderoAppSecret = null;
        String xEmbarcaderoMasterSecret = null;
        api.aPI(xEmbarcaderoApplicationId, xEmbarcaderoAppSecret, xEmbarcaderoMasterSecret);

        // TODO: test validations
    }
    
    /**
     * Get JSON
     *
     * Get API in JSON format
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAPIJSONFormatTest() throws ApiException {
        String xEmbarcaderoApplicationId = null;
        String xEmbarcaderoAppSecret = null;
        String xEmbarcaderoMasterSecret = null;
        api.getAPIJSONFormat(xEmbarcaderoApplicationId, xEmbarcaderoAppSecret, xEmbarcaderoMasterSecret);

        // TODO: test validations
    }
    
    /**
     * Get YAML
     *
     * Get API in YAML format
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAPIYAMLFormatTest() throws ApiException {
        String xEmbarcaderoApplicationId = null;
        String xEmbarcaderoAppSecret = null;
        String xEmbarcaderoMasterSecret = null;
        api.getAPIYAMLFormat(xEmbarcaderoApplicationId, xEmbarcaderoAppSecret, xEmbarcaderoMasterSecret);

        // TODO: test validations
    }
    
    /**
     * Get API EndPoint
     *
     *  |      Used to retrieve an EndPoint for the API EndPoints.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAPIYAMLFormatEndPointTest() throws ApiException {
        String item = null;
        String xEmbarcaderoApplicationId = null;
        String xEmbarcaderoAppSecret = null;
        String xEmbarcaderoMasterSecret = null;
        api.getAPIYAMLFormatEndPoint(item, xEmbarcaderoApplicationId, xEmbarcaderoAppSecret, xEmbarcaderoMasterSecret);

        // TODO: test validations
    }
    
}
