# coding: utf-8

"""
    EMS API Documentation

    Enterprise Mobility Services API      [Learn about EMS](https://www.embarcadero.com/products/rad-studio/enterprise-mobility-services)      EMS (Enterprise Mobility Services) offers a Mobile Enterprise Application Platform (MEAP)      TurnKey Middleware for Interconnected Distributed Apps  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.installations_api import InstallationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInstallationsApi(unittest.TestCase):
    """InstallationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.installations_api.InstallationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_installation(self):
        """Test case for add_installation

        Add Installation  # noqa: E501
        """
        pass

    def test_delete_installation(self):
        """Test case for delete_installation

        Delete Installation  # noqa: E501
        """
        pass

    def test_get_channels(self):
        """Test case for get_channels

        Get Installation Channels  # noqa: E501
        """
        pass

    def test_get_installation(self):
        """Test case for get_installation

        Get Installation  # noqa: E501
        """
        pass

    def test_get_installation_fields(self):
        """Test case for get_installation_fields

        Get Fields  # noqa: E501
        """
        pass

    def test_get_installations(self):
        """Test case for get_installations

        Get Installations  # noqa: E501
        """
        pass

    def test_update_installation(self):
        """Test case for update_installation

        Update Installation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
